-- QUANTIDADE DE APRESENTADORES POR COMISSAO, SENDO A COMISSÃO MAIOR QUE 500 (GROUP BY/HAVING)
SELECT COMISSAO, COUNT(*) AS QTD_APRESENTADOR
FROM APRESENTADOR
GROUP BY COMISSAO
HAVING COMISSAO > 500;

-- NOME DOS FUNCIONARIOS QUEM COMEÇAM COM 'A' QUE SÃO RESPONSÁVEIS POR SALAS (JUNÇÃO INTERNA)
SELECT  F.NOME, S.NUMERO AS SALA
FROM FUNCIONARIO F INNER JOIN SALA S ON F.CPF = S.CPF
WHERE F.NOME LIKE 'A%';

-- NUMERO DAS SALAS SEM FUNCIONARIO (JUNÇÃO EXTERNA A DIREITA)
SELECT  F.NOME, S.NUMERO  AS SALA
FROM FUNCIONARIO F RIGHT OUTER JOIN SALA S ON F.CPF = S.CPF
WHERE S.CPF IS NULL;

-- NOME E SALARIO DOS FUNCIONARIOS QUE RECEBEM MAIS DO QUE A MÉDIA DOS SALARIOS (SUBCONSULTA ESCALAR)
SELECT NOME, SALARIO
FROM FUNCIONARIO
WHERE SALARIO >
    (SELECT AVG(SALARIO)
    FROM FUNCIONARIO);

-- NOME DOS FUNCIONARIOS QUE TEM O MESMO CHEFE E SALARIO QUE O FUNCIONARIO 0002 (SUBCONSULTA LINHA)
SELECT NOME, CPF_CHEFE, SALARIO
FROM FUNCIONARIO
WHERE (CPF_CHEFE, SALARIO) =
    (SELECT CPF_CHEFE, SALARIO
    FROM FUNCIONARIO
    WHERE CPF = 0002);

-- NOME DOS APRESENTADORES EXCETO O QUE TEM MAIOR COMISSAO (SUBCONSULTA TABELA)
SELECT NOME, COMISSAO
FROM APRESENTADOR
WHERE COMISSAO < ANY
    (SELECT COMISSAO
    FROM APRESENTADOR);

-- NOME DOS EVENTOS QUE POSSUEM SEÇÕES CADASTRADAS (SEMI JUNÇÃO)
SELECT E.NOME
FROM EVENTOCONTRATO E
WHERE EXISTS
    (SELECT *
    FROM SECAO S
    WHERE E.COD_EV = S.COD_EV);

-- NOME DOS APRESENTADORES QUE NÃO POSSUEM APRESENTAÇÃO CADASTRADA (ANTI JUNÇÃO)
SELECT A.NOME
FROM APRESENTADOR A
WHERE NOT EXISTS
    (SELECT *
    FROM APRESENTACAO AP
    WHERE A.CPF = AP.CPF_APRESENTADOR);

-- NOME E CPF DAS PESSOAS QUE TEM NOME COMEÇANDO COM A LETRA 'A' E É FUNCIONÁRIO OU OUVINTE (CONJUNTOS)
    (SELECT NOME, CPF
    FROM FUNCIONARIO
    WHERE NOME LIKE 'A%')
UNION
    (SELECT NOME, CPF
    FROM OUVINTE
    WHERE NOME LIKE 'A%');
