--GATILHOS

UPDATE DESCONTO SET PORCENTAGEM = PORCENTAGEM + 0.05;

INSERT INTO APRESENTADOR VALUES (0444, 'D_A', 'DA@gmail.com', 50047000, 17595480, 500);

UPDATE APRESENTADOR SET NOME = 'E_A', EMAIL = 'EA@gmail.com' WHERE CPF = 0444;

UPDATE APRESENTADOR SET COMISSAO = COMISSAO + 200 WHERE CPF = 0444;

INSERT INTO OUVINTE (CPF, NOME, EMAIL, TELEFONE1) VALUES (0224, 'D_O', 'DO@gmail.com', 10001000);

INSERT INTO OUVINTE VALUES (0225, 'E_O', 'EO@gmail.com', 15485687, 90048568);

INSERT INTO OUVINTE VALUES (0226, 'F_O', 'FO@gmail.com', 35478964, 14789614);

DELETE FROM OUVINTE WHERE CPF = 0226;

INSERT INTO SALA VALUES (04, 0113);

UPDATE EventoContrato SET NOME = 'NOVONOME' WHERE COD_EV = 0003;

UPDATE OUVINTE SET TELEFONE2 = 15785445 WHERE CPF = 0222;

INSERT INTO INGRESSO VALUES (04, 25.50);

INSERT INTO COMPRA VALUES (0225, 04, NULL);

DELETE FROM COMPRA WHERE CPF_OUVINTE = 0225 AND QR_CODE = 04;

DELETE FROM INGRESSO WHERE QR_CODE = 04;

--FUNÇÕES

-- Função para contar quantos eventos um funcionário participa
CREATE OR REPLACE FUNCTION CONTAR_EVENTOS_FUNCIONARIO(
    P_CPF NUMBER  
) RETURN NUMBER IS
    V_TOTAL NUMBER; 
BEGIN
    SELECT COUNT(*) INTO V_TOTAL
    FROM TRABALHA
    WHERE CPF = P_CPF;
	
    RETURN V_TOTAL;
END;
/
----------------------------------------------------------
CREATE OR REPLACE FUNCTION TOTAL_VENDAS
RETURN NUMBER IS  -- Aqui estava o erro: usar "IS" ao invés de "AS"
    total NUMBER;
BEGIN
    SELECT COALESCE(SUM(i.VALOR), 0) INTO total
    FROM COMPRA c
    JOIN INGRESSO i ON c.QR_CODE = i.QR_CODE;

    RETURN total;
END;
/
    
CREATE OR REPLACE FUNCTION OUVINTE_COMPROU_INGRESSO(p_cpf NUMBER)
RETURN VARCHAR AS
    existe NUMBER;
BEGIN
    SELECT COUNT(*) INTO existe FROM COMPRA WHERE CPF_OUVINTE = p_cpf;
    
    IF existe > 0 THEN
        RETURN 'SIM';
    ELSE
        RETURN 'NÃO';
    END IF;
END;
/
    
CREATE OR REPLACE FUNCTION CONTAR_INGRESSOS_VENDIDOS
RETURN NUMBER IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM COMPRA;
    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION OUVINTE_EXISTE(
    P_CPF NUMBER
) RETURN NUMBER IS
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTE FROM OUVINTE WHERE CPF = P_CPF;
    
    IF V_EXISTE > 0 THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/