-- Procedure para cadastrar um novo Ouvinte 

CREATE OR REPLACE TYPE TELEFONE_ARRAY AS VARRAY(2) OF NUMBER(8);

CREATE OR REPLACE PROCEDURE CADASTRAR_OUVINTE ( 
    P_CPF IN OUVINTE.CPF%TYPE, 
    P_NOME IN OUVINTE.NOME%TYPE, 
    P_EMAIL IN OUVINTE.EMAIL%TYPE, 
    P_TELEFONE IN TELEFONE_ARRAY 
) IS 
BEGIN 
    INSERT INTO OUVINTE (CPF, NOME, EMAIL, TELEFONE1, TELEFONE2) 
    VALUES (P_CPF, P_NOME, P_EMAIL, P_TELEFONE(1), P_TELEFONE(2)); 
 
    DBMS_OUTPUT.PUT_LINE('OUVINTE CADASTRADO COM SUCESSO'); 
END CADASTRAR_OUVINTE; 
/

-- Procedure para cadastrar um novo Apresentador

CREATE OR REPLACE PROCEDURE CADASTRAR_APRESENTADOR ( 
    P_CPF IN APRESENTADOR.CPF%TYPE, 
    P_NOME IN APRESENTADOR.NOME%TYPE, 
    P_EMAIL IN APRESENTADOR.EMAIL%TYPE, 
    P_COMISSAO IN APRESENTADOR.COMISSAO%TYPE, 
    P_TELEFONE IN TELEFONE_ARRAY 
) IS 
BEGIN 
    INSERT INTO APRESENTADOR (CPF, NOME, EMAIL, COMISSAO, TELEFONE1, TELEFONE2) 
    VALUES (P_CPF, P_NOME, P_EMAIL, P_COMISSAO, P_TELEFONE(1), P_TELEFONE(2)); 
 
    DBMS_OUTPUT.PUT_LINE('APRESENTADOR CADASTRADO COM SUCESSO'); 
END CADASTRAR_APRESENTADOR; 
 
-- Procedure para cadastrar um novo Funcionário  
 
CREATE OR REPLACE PROCEDURE CADASTRAR_FUNCIONARIO ( 
    P_CPF IN FUNCIONARIO.CPF%TYPE, 
    P_NOME IN FUNCIONARIO.NOME%TYPE, 
    P_EMAIL IN FUNCIONARIO.EMAIL%TYPE, 
    P_SALARIO IN FUNCIONARIO.SALARIO%TYPE, 
    P_TELEFONE IN TELEFONE_ARRAY 
) IS 
BEGIN 
    INSERT INTO FUNCIONARIO (CPF, NOME, EMAIL, SALARIO, TELEFONE1, TELEFONE2) 
    VALUES (P_CPF, P_NOME, P_EMAIL, P_SALARIO, P_TELEFONE(1), P_TELEFONE(2)); 
 
    DBMS_OUTPUT.PUT_LINE('FUNCIONARIO CADASTRADO COM SUCESSO'); 
END CADASTRAR_FUNCIONARIO; 
 
 
-- Procedure que vai retornar a qtd de ingressos vendidos 
 
CREATE OR REPLACE PROCEDURE RETORNAR_QTD_INGRESSOS_VENDIDOS ( 
    P_QTD_INGRESSOS OUT NUMBER 
) IS 
BEGIN 
    -- Conta a quantidade total de ingressos vendidos na tabela COMPRA 
    SELECT COUNT(*) INTO P_QTD_INGRESSOS 
    FROM COMPRA; 
 
EXCEPTION 
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('Erro: ' || SQLERRM); 
END RETORNAR_QTD_INGRESSOS_VENDIDOS;
/

